# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  install-deps-client:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          client-cache-name: cache-client-node-modules
        with:
          path: ./client/node_modules
          key: npm-${{ env.client-cache-name }}-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            npm-${{ env.client-cache-name }}-${{ hashFiles('client/package-lock.json') }}
      - run: npm i --prefix client

  install-deps-root:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          root-cache-name: cache-root-node-modules
        with:
          path: ./node_modules
          key: npm-${{ env.root-cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ env.root-cache-name }}-${{ hashFiles('package-lock.json') }}
      - run: npm i

  install-deps-server:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          server-cache-name: cache-server-node-modules
        with:
          path: ./server/node_modules
          key: npm-${{ env.server-cache-name }}-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            npm-${{ env.server-cache-name }}-${{ hashFiles('server/package-lock.json') }}
      - run: npm i --prefix server

  # client
  lint-client:
    needs: install-deps-client
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          client-cache-name: cache-client-node-modules
        with:
          path: ./client/node_modules
          key: npm-${{ env.client-cache-name }}-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            npm-${{ env.client-cache-name }}-${{ hashFiles('client/package-lock.json') }}
      - run: npm run lint --prefix client

  test-client:
    needs: install-deps-client
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          client-cache-name: cache-client-node-modules
        with:
          path: ./client/node_modules
          key: npm-${{ env.client-cache-name }}-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            npm-${{ env.client-cache-name }}-${{ hashFiles('client/package-lock.json') }}
      - run: npm run test --prefix client

  flow-client:
    needs: install-deps-client
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          client-cache-name: cache-client-node-modules
        with:
          path: ./client/node_modules
          key: npm-${{ env.client-cache-name }}-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            npm-${{ env.client-cache-name }}-${{ hashFiles('client/package-lock.json') }}
      - run: npm run flow --prefix client

  build-client:
    needs: install-deps-client
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          client-cache-name: cache-client-node-modules
        with:
          path: ./client/node_modules
          key: npm-${{ env.client-cache-name }}-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            npm-${{ env.client-cache-name }}-${{ hashFiles('client/package-lock.json') }}
      - run: npm run build --prefix client

  # server
  lint-server:
    needs: install-deps-server
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          server-cache-name: cache-server-node-modules
        with:
          path: ./server/node_modules
          key: npm-${{ env.server-cache-name }}-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            npm-${{ env.server-cache-name }}-${{ hashFiles('server/package-lock.json') }}
      - run: npm run lint --prefix server

  test-server:
    needs: install-deps-server
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          server-cache-name: cache-server-node-modules
        with:
          path: ./server/node_modules
          key: npm-${{ env.server-cache-name }}-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            npm-${{ env.server-cache-name }}-${{ hashFiles('server/package-lock.json') }}
      - run: npm run test --prefix server
